const fs = require('fs');
const path = require('path');

const locales = {
  en: {
    dashboard: "Dashboard", inventory: "Inventory", orders: "Orders", accounting: "Accounting", marketing: "Marketing", courier: "Courier", reports: "Reports", settings: "Settings", logout: "Logout",
    business_analytics: "Business Analytics", sales_vs_profit_title: "Sales vs Profit (Last 7 Orders)", sales: "Sales", profit: "Profit", expense_breakdown: "Expense Breakdown", generating_charts: "Generating Charts...", revenue: "Revenue", net_profit: "Net Profit",
    business_profile: "Business Profile", company_title: "Company Title", base_currency: "Base Currency", identity_access: "Identity & Access", full_name: "Full Name", email_address: "Email Address", localization: "Localization", auto_sync_enabled: "Auto-Sync Enabled", save_settings: "Save Settings", syncing: "Syncing...", settings_saved_success: "Settings saved successfully!",
    create_new_order: "Create New Order", customer_name: "Customer Name", phone_number: "Phone Number", select_product: "Select Product", select_a_product: "Select a Product", stock: "Stock", quantity: "Quantity", discount: "Discount", confirm_order: "Confirm Order", recent_orders: "Recent Orders", customer: "Customer", product: "Product", status: "Status", action: "Action", pending: "Pending", delivered: "Delivered", cancelled: "Cancelled", order_date: "Order Date", price: "Price", total: "Total",
    add_product: "Add Product", product_name: "Product Name", buying_price: "Buying Price", selling_price: "Selling Price", category: "Category", stock_status: "Stock Status", in_stock: "In Stock", out_of_stock: "Out of Stock", update_stock: "Update Stock",
    total_balance: "Total Balance", income: "Income", expense: "Expense", add_expense: "Add Expense", category_name: "Category Name", amount: "Amount", date: "Date", description: "Description",
    shipping_status: "Shipping Status", track_order: "Track Order", tracking_id: "Tracking ID", delivery_charge: "Delivery Charge", courier_name: "Courier Name",
    ad_cost: "Ad Cost", conversion_rate: "Conversion Rate", reach: "Reach", leads: "Leads", campaign_name: "Campaign Name", marketing_roi: "Marketing ROI"
  },
  bn: {
    dashboard: "ড্যাশবোর্ড", inventory: "ইনভেন্টরি", orders: "অর্ডারসমূহ", accounting: "অ্যাকাউন্টিং", marketing: "মার্কেটিং", courier: "কুরিয়ার", reports: "রিপোর্টস", settings: "সেটিংস", logout: "লগআউট",
    business_analytics: "বিজনেস অ্যানালিটিক্স", sales_vs_profit_title: "বিক্রয় বনাম লাভ (শেষ ৭ অর্ডার)", sales: "বিক্রয়", profit: "লাভ", expense_breakdown: "খরচের বিবরণ", generating_charts: "চার্ট তৈরি হচ্ছে...", revenue: "রাজস্ব", net_profit: "নিট মুনাফা",
    business_profile: "বিজনেস প্রোফাইল", company_title: "কোম্পানির নাম", base_currency: "মূল কারেন্সি", identity_access: "পরিচয় ও প্রবেশাধিকার", full_name: "পুরো নাম", email_address: "ইমেইল এড্রেস", localization: "লোকালাইজেশন", auto_sync_enabled: "অটো-সিঙ্ক চালু আছে", save_settings: "সেটিংস সেভ করুন", syncing: "সিঙ্ক হচ্ছে...", settings_saved_success: "সেটিংস সফলভাবে সংরক্ষিত হয়েছে!",
    create_new_order: "নতুন অর্ডার তৈরি করুন", customer_name: "কাস্টমারের নাম", phone_number: "ফোন নম্বর", select_product: "পণ্য নির্বাচন করুন", select_a_product: "একটি পণ্য বেছে নিন", stock: "স্টক", quantity: "পরিমাণ", discount: "ডিসকাউন্ট", confirm_order: "অর্ডার কনফার্ম করুন", recent_orders: "সাম্প্রতিক অর্ডারসমূহ", customer: "কাস্টমার", product: "পণ্য", status: "স্ট্যাটাস", action: "অ্যাকশন", pending: "পেন্ডিং", delivered: "ডেলিভারড", cancelled: "বাতিল", order_date: "অর্ডারের তারিখ", price: "মূল্য", total: "মোট",
    add_product: "পণ্য যোগ করুন", product_name: "পণ্যের নাম", buying_price: "ক্রয় মূল্য", selling_price: "বিক্রয় মূল্য", category: "ক্যাটাগরি", stock_status: "স্টক স্ট্যাটাস", in_stock: "স্টকে আছে", out_of_stock: "স্টক নেই", update_stock: "স্টক আপডেট",
    total_balance: "মোট ব্যালেন্স", income: "আয়", expense: "ব্যয়", add_expense: "খরচ যোগ করুন", category_name: "ক্যাটাগরির নাম", amount: "পরিমাণ", date: "তারিখ", description: "বিবরণ",
    shipping_status: "শিপিং স্ট্যাটাস", track_order: "অর্ডার ট্র্যাক করুন", tracking_id: "ট্র্যাকিং আইডি", delivery_charge: "ডেলিভারি চার্জ", courier_name: "কুরিয়ার কোম্পানির নাম",
    ad_cost: "বিজ্ঞাপন খরচ", conversion_rate: "কনভার্সন রেট", reach: "রিচ", leads: "লিডস", campaign_name: "ক্যাম্পেইন নাম", marketing_roi: "মার্কেটিং আরওআই"
  },
  ar: {
    dashboard: "لوحة القيادة", inventory: "المخزون", orders: "الطلبات", accounting: "المحاسبة", marketing: "التسويق", courier: "الشحن", reports: "التقارير", settings: "الإعدادات", logout: "تسجيل الخروج",
    business_analytics: "تحليلات الأعمال", sales_vs_profit_title: "المبيعات مقابل الربح (آخر 7 طلبات)", sales: "المبيعات", profit: "الربح", expense_breakdown: "تفصيل المصاريف", generating_charts: "جاري إنشاء المخططات...", revenue: "إيرادات", net_profit: "صافي الربح",
    business_profile: "ملف العمل", company_title: "اسم الشركة", base_currency: "العملة الأساسية", identity_access: "الهوية والوصول", full_name: "الاسم الكامل", email_address: "البريد الإلكتروني", localization: "الموقع", auto_sync_enabled: "المزامنة التلقائية مفعلة", save_settings: "حفظ الإعدادات", syncing: "جاري المزامنة...", settings_saved_success: "تم حفظ الإعدادات بنجاح!",
    create_new_order: "إنشاء طلب جديد", customer_name: "اسم العميل", phone_number: "رقم الهاتف", select_product: "اختر المنتج", select_a_product: "اختر منتجًا", stock: "المخزون", quantity: "الكمية", discount: "خصم", confirm_order: "تأكيد الطلب", recent_orders: "الطلبات الأخيرة", customer: "العميل", product: "المنتج", status: "الحالة", action: "إجراء", pending: "قيد الانتظار", delivered: "تم التوصيل", cancelled: "ملغي", order_date: "تاريخ الطلب", price: "السعر", total: "الإجمالي",
    add_product: "إضافة منتج", product_name: "اسم المنتج", buying_price: "سعر الشراء", selling_price: "سعر البيع", category: "الفئة", stock_status: "حالة المخزون", in_stock: "في المخزن", out_of_stock: "نفد من المخزن", update_stock: "تحديث المخزون",
    total_balance: "الرصيد الإجمالي", income: "الدخل", expense: "المصاريف", add_expense: "إضافة مصروف", category_name: "اسم الفئة", amount: "المبلغ", date: "التاريخ", description: "الوصف",
    shipping_status: "حالة الشحن", track_order: "تتبع الطلب", tracking_id: "رقم التتبع", delivery_charge: "رسوم التوصيل", courier_name: "اسم شركة الشحن",
    ad_cost: "تكلفة الإعلان", conversion_rate: "معدل التحويل", reach: "الوصول", leads: "العملاء المحتملون", campaign_name: "اسم الحملة", marketing_roi: "عائد الاستثمار التسويقي"
  },
  ur: {
    dashboard: "ڈیش بورڈ", inventory: "انوینٹری", orders: "آرڈرز", accounting: "اکاؤنٹنگ", marketing: "مارکیٹنگ", courier: "کوریئر", reports: "رپورٹس", settings: "ترتیبات", logout: "لاگ آؤٹ",
    business_analytics: "کاروباری تجزیات", sales_vs_profit_title: "فروخت بمقابلہ منافع (آخری 7 آرڈرز)", sales: "فروخت", profit: "منافع", expense_breakdown: "اخراجات کی تفصیل", generating_charts: "چارٹس بن رہے ہیں...", revenue: "آمدنی", net_profit: "خالص منافع",
    business_profile: "بزنس پروفائل", company_title: "کمپنی کا نام", base_currency: "بنیادی کرنسی", identity_access: "شناخت اور رسائی", full_name: "پورا نام", email_address: "ای میل ایڈریس", localization: "لوکلائزیشن", auto_sync_enabled: "آٹو سنک فعال ہے", save_settings: "ترتیبات محفوظ کریں", syncing: "سنک ہو رہا ہے...", settings_saved_success: "ترتیبات کامیابی سے محفوظ ہوگئیں!",
    create_new_order: "نیا آرڈر بنائیں", customer_name: "کسٹمر کا نام", phone_number: "فون نمبر", select_product: "پروڈکٹ منتخب کریں", select_a_product: "پروڈکٹ کا انتخاب کریں", stock: "اسٹاک", quantity: "مقدار", discount: "رعایت", confirm_order: "آرڈر کی تصدیق کریں", recent_orders: "حالیہ آرڈرز", customer: "کسٹمر", product: "پروڈکٹ", status: "صورتحال", action: "ایکشن", pending: "زیر التواء", delivered: "ڈیلیور ہو گیا", cancelled: "منسوخ", order_date: "آرڈر کی تاریخ", price: "قیمت", total: "کل",
    add_product: "پروڈکٹ شامل کریں", product_name: "پروڈکٹ کا نام", buying_price: "خریداری کی قیمت", selling_price: "فروخت کی قیمت", category: "زمرہ", stock_status: "اسٹاک کی حالت", in_stock: "اسٹاک میں ہے", out_of_stock: "اسٹاک ختم", update_stock: "اسٹاک اپ ڈیٹ",
    total_balance: "کل بیلنس", income: "آمدنی", expense: "خرچہ", add_expense: "خرچہ شامل کریں", category_name: "زمرہ کا نام", amount: "رقم", date: "تاریخ", description: "تفصیل",
    shipping_status: "شپنگ کی صورتحال", track_order: "آرڈر ٹریک کریں", tracking_id: "ٹریکنگ آئی ڈی", delivery_charge: "ڈلیوری چارج", courier_name: "کوریئر کا نام",
    ad_cost: "اشتہار کی لاگت", conversion_rate: "تبدیلی کی شرح", reach: "رسائی", leads: "لیڈز", campaign_name: "کیمپین کا نام", marketing_roi: "مارکیٹنگ ROI"
  },
  ps: {
    dashboard: "ډیش بورډ", inventory: "انوینٹری", orders: "سپارښتنې", accounting: "محاسبه", marketing: "بازارموندنه", courier: "قاصد", reports: "راپورونه", settings: "تنظیمات", logout: "وتل",
    business_analytics: "د سوداګرۍ تحلیل", sales_vs_profit_title: "پلور او ګټه (وروستي 7 سپارښتنې)", sales: "پلور", profit: "ګټه", expense_breakdown: "د لګښتونو تفصیل", generating_charts: "چارټونه جوړیږي...", revenue: "عواید", net_profit: "خالصه ګټه",
    business_profile: "د سوداګرۍ پروفایل", company_title: "د شرکت نوم", base_currency: "اساسي اسعار", identity_access: "پیژندنه او لاسرسی", full_name: "بشپړ نوم", email_address: "د بریښنالیک پته", localization: "ځایی کول", auto_sync_enabled: "اتوماتیک همغږي فعاله ده", save_settings: "تنظیمات خوندي کړئ", syncing: "همغږي کیږي...", settings_saved_success: "تنظیمات په بریالیتوب سره خوندي شول!",
    create_new_order: "نوې سپارښتنه جوړه کړئ", customer_name: "د پیرودونکي نوم", phone_number: "د تلیفون شمیره", select_product: "محصول غوره کړئ", select_a_product: "یو محصول غوره کړئ", stock: "سټاک", quantity: "مقدار", discount: "خفیف", confirm_order: "سپارښتنه تایید کړئ", recent_orders: "وروستي سپارښتنې", customer: "پیرودونکی", product: "محصول", status: "حالت", action: "عمل", pending: "نيمګړی", delivered: "رسول شوی", cancelled: "لغوه شوی", order_date: "د سپارښتنې نیټه", price: "بیه", total: "ټول",
    add_product: "محصول اضافه کړئ", product_name: "د محصول نوم", buying_price: "د پیرود قیمت", selling_price: "د پلور قیمت", category: "کټګورۍ", stock_status: "د سټاک حالت", in_stock: "په سټاک کې شتون لري", out_of_stock: "سټاک خلاص شوی", update_stock: "سټاک تازه کول",
    total_balance: "ټول بیلانس", income: "عواید", expense: "لګښت", add_expense: "لګښت اضافه کړئ", category_name: "د کټګورۍ نوم", amount: "اندازه", date: "نیټه", description: "تفصیل",
    shipping_status: "د لیږد حالت", track_order: "سپارښتنه تعقیب کړئ", tracking_id: "د تعقیب ID", delivery_charge: "د رسولو لګښت", courier_name: "د قاصد شرکت نوم",
    ad_cost: "د اعلان لګښت", conversion_rate: "د تبادلې کچه", reach: "رسیدنه", leads: "لیډز", campaign_name: "د کمپاین نوم", marketing_roi: "بازارموندنه ROI"
  },
  hi: {
    dashboard: "डैशबोर्ड", inventory: "इन्वेंट्री", orders: "आदेश", accounting: "अकाउंटिंग", marketing: "मार्केटिंग", courier: "कूरियर", reports: "रिपोर्ट्स", settings: "सेटिंग्स", logout: "लॉगआउट",
    business_analytics: "बिजनेस एनालिटिक्स", sales_vs_profit_title: "बिक्री बनाम लाभ (पिछले 7 ऑर्डर)", sales: "बिक्री", profit: "लाभ", expense_breakdown: "व्यय विवरण", generating_charts: "चार्ट बनाए जा रहे हैं...", revenue: "राजस्व", net_profit: "शुद्ध लाभ",
    business_profile: "बिजनेस प्रोफाइल", company_title: "कंपनी का नाम", base_currency: "आधार मुद्रा", identity_access: "पहचान और पहुंच", full_name: "पूरा नाम", email_address: "ईमेल पता", localization: "स्थानीयकरण", auto_sync_enabled: "ऑटो-सिंक सक्षम है", save_settings: "सेटिंग्स सहेजें", syncing: "सिंक हो रहा है...", settings_saved_success: "सेटिंग्स सफलतापूर्वक सहेजी गईं!",
    create_new_order: "नया ऑर्डर बनाएं", customer_name: "ग्राहक का नाम", phone_number: "फ़ोन नंबर", select_product: "उत्पाद चुनें", select_a_product: "एक उत्पाद चुनें", stock: "स्टॉक", quantity: "मात्रा", discount: "छूट", confirm_order: "ऑर्डर की पुष्टि करें", recent_orders: "हाल के आदेश", customer: "ग्राहक", product: "उत्पाद", status: "स्थिति", action: "कार्रवाई", pending: "लंबित", delivered: "वितरित", cancelled: "रद्द", order_date: "ऑर्डर की तारीख", price: "कीमत", total: "कुल",
    add_product: "उत्पाद जोड़ें", product_name: "उत्पाद का नाम", buying_price: "खरीद मूल्य", selling_price: "विक्रय मूल्य", category: "श्रेणी", stock_status: "स्टॉक स्थिति", in_stock: "स्टॉक में", out_of_stock: "स्टॉक में नहीं", update_stock: "स्टॉक अपडेट करें",
    total_balance: "कुल शेष", income: "आय", expense: "व्यय", add_expense: "व्यय जोड़ें", category_name: "श्रेणी का नाम", amount: "राशि", date: "तारीख", description: "विवरण",
    shipping_status: "शिपिंग स्थिति", track_order: "ऑर्डर ट्रैक करें", tracking_id: "ट्रैकिंग आईडी", delivery_charge: "डिलिवरी शुल्क", courier_name: "कूरियर का नाम",
    ad_cost: "विज्ञापन लागत", conversion_rate: "रूपांतरण दर", reach: "पहुंच", leads: "लीड्स", campaign_name: "अभियान का नाम", marketing_roi: "मार्केटिंग ROI"
  },
  ru: {
    dashboard: "Дашборд", inventory: "Инвентарь", orders: "Заказы", accounting: "Бухгалтерия", marketing: "Маркетинг", courier: "Курьер", reports: "Отчеты", settings: "Настройки", logout: "Выйти",
    business_analytics: "Бизнес-аналитика", sales_vs_profit_title: "Продажи против прибыли (7 заказов)", sales: "Продажи", profit: "Прибыль", expense_breakdown: "Расходы", generating_charts: "Создание графиков...", revenue: "Выручка", net_profit: "Чистая прибыль",
    business_profile: "Бизнес-профиль", company_title: "Название компании", base_currency: "Валюта", identity_access: "Доступ", full_name: "Полное имя", email_address: "Email", localization: "Локализация", auto_sync_enabled: "Автосинхронизация", save_settings: "Сохранить", syncing: "Синхронизация...", settings_saved_success: "Успешно сохранено!",
    create_new_order: "Создать заказ", customer_name: "Имя клиента", phone_number: "Телефон", select_product: "Выбрать товар", select_a_product: "Выберите товар", stock: "Склад", quantity: "Кол-во", discount: "Скидка", confirm_order: "Подтвердить", recent_orders: "Заказы", customer: "Клиент", product: "Товар", status: "Статус", action: "Действие", pending: "Ожидание", delivered: "Доставлено", cancelled: "Отменено", order_date: "Дата", price: "Цена", total: "Итого",
    add_product: "Добавить товар", product_name: "Название товара", buying_price: "Цена закупки", selling_price: "Цена продажи", category: "Категория", stock_status: "Статус склада", in_stock: "В наличии", out_of_stock: "Нет в наличии", update_stock: "Обновить",
    total_balance: "Баланс", income: "Доход", expense: "Расход", add_expense: "Добавить расход", category_name: "Категория", amount: "Сумма", date: "Дата", description: "Описание",
    shipping_status: "Доставка", track_order: "Отследить", tracking_id: "Трекинг ID", delivery_charge: "Цена доставки", courier_name: "Курьер",
    ad_cost: "Реклама", conversion_rate: "Конверсия", reach: "Охват", leads: "Лиды", campaign_name: "Кампания", marketing_roi: "Маркетинг ROI"
  },
  zh: {
    dashboard: "仪表板", inventory: "库存", orders: "订单", accounting: "会计", marketing: "营销", courier: "快递", reports: "报告", settings: "设置", logout: "注销",
    business_analytics: "业务分析", sales_vs_profit_title: "销售额与利润（最近 7 个订单）", sales: "销售额", profit: "利润", expense_breakdown: "费用明细", generating_charts: "正在生成图表...", revenue: "收入", net_profit: "净利润",
    business_profile: "业务概况", company_title: "公司名称", base_currency: "基础货币", identity_access: "身份与访问", full_name: "全名", email_address: "电子邮件", localization: "本地化", auto_sync_enabled: "自动同步已启用", save_settings: "保存设置", syncing: "正在同步...", settings_saved_success: "设置保存成功！",
    create_new_order: "创建新订单", customer_name: "客户姓名", phone_number: "电话号码", select_product: "选择产品", select_a_product: "选择一个产品", stock: "库存", quantity: "数量", discount: "折扣", confirm_order: "确认订单", recent_orders: "最近订单", customer: "客户", product: "产品", status: "状态", action: "操作", pending: "待处理", delivered: "已送达", cancelled: "已取消", order_date: "订单日期", price: "价格", total: "总计",
    add_product: "添加产品", product_name: "产品名称", buying_price: "买入价", selling_price: "零售价", category: "类别", stock_status: "库存状态", in_stock: "有货", out_of_stock: "缺货", update_stock: "更新库存",
    total_balance: "总余额", income: "收入", expense: "支出", add_expense: "添加支出", category_name: "类别名称", amount: "金额", date: "日期", description: "描述",
    shipping_status: "发货状态", track_order: "追踪订单", tracking_id: "追踪 ID", delivery_charge: "运费", courier_name: "快递名称",
    ad_cost: "广告成本", conversion_rate: "转化率", reach: "覆盖范围", leads: "潜在客户", campaign_name: "活动名称", marketing_roi: "营销投资回报率"
  },
  es: {
    dashboard: "Panel", inventory: "Inventario", orders: "Pedidos", accounting: "Contabilidad", marketing: "Marketing", courier: "Mensajería", reports: "Reportes", settings: "Ajustes", logout: "Cerrar sesión",
    business_analytics: "Analítica", sales_vs_profit_title: "Ventas vs Ganancias (7 pedidos)", sales: "Ventas", profit: "Ganancias", expense_breakdown: "Gastos", generating_charts: "Generando...", revenue: "Ingresos", net_profit: "Ganancia neta",
    business_profile: "Perfil", company_title: "Empresa", base_currency: "Moneda", identity_access: "Acceso", full_name: "Nombre", email_address: "Email", localization: "Localización", auto_sync_enabled: "Sincronización activa", save_settings: "Guardar", syncing: "Sincronizando...", settings_saved_success: "¡Guardado!",
    create_new_order: "Nuevo pedido", customer_name: "Cliente", phone_number: "Teléfono", select_product: "Producto", select_a_product: "Selecciona producto", stock: "Stock", quantity: "Cantidad", discount: "Descuento", confirm_order: "Confirmar", recent_orders: "Pedidos", customer: "Cliente", product: "Producto", status: "Estado", action: "Acción", pending: "Pendiente", delivered: "Entregado", cancelled: "Cancelado", order_date: "Fecha", price: "Precio", total: "Total",
    add_product: "Añadir producto", product_name: "Nombre", buying_price: "Precio compra", selling_price: "Precio venta", category: "Categoría", stock_status: "Stock estado", in_stock: "En stock", out_of_stock: "Sin stock", update_stock: "Actualizar stock",
    total_balance: "Saldo", income: "Ingresos", expense: "Gastos", add_expense: "Añadir gasto", category_name: "Categoría", amount: "Cantidad", date: "Fecha", description: "Descripción",
    shipping_status: "Envío", track_order: "Rastrear", tracking_id: "ID Rastro", delivery_charge: "Costo envío", courier_name: "Mensajería",
    ad_cost: "Costo publicidad", conversion_rate: "Tasa conversión", reach: "Alcance", leads: "Leads", campaign_name: "Campaña", marketing_roi: "Marketing ROI"
  },
  ja: {
    dashboard: "ダッシュボード", inventory: "在庫", orders: "注文", accounting: "会計", marketing: "マーケティング", courier: "配送", reports: "レポート", settings: "設定", logout: "ログアウト",
    business_analytics: "ビジネス分析", sales_vs_profit_title: "売上対利益（直近7件）", sales: "売上", profit: "利益", expense_breakdown: "経費内訳", generating_charts: "生成中...", revenue: "収益", net_profit: "純利益",
    business_profile: "プロファイル", company_title: "会社名", base_currency: "通貨", identity_access: "アクセス", full_name: "氏名", email_address: "メール", localization: "地域", auto_sync_enabled: "自動同期有効", save_settings: "保存", syncing: "同期中...", settings_saved_success: "保存完了！",
    create_new_order: "新規注文", customer_name: "顧客名", phone_number: "電話番号", select_product: "商品選択", select_a_product: "商品を選択", stock: "在庫", quantity: "数量", discount: "割引", confirm_order: "確定", recent_orders: "最近の注文", customer: "顧客", product: "商品", status: "状態", action: "操作", pending: "保留中", delivered: "配達済", cancelled: "キャンセル", order_date: "注文日", price: "価格", total: "合計",
    add_product: "商品追加", product_name: "商品名", buying_price: "仕入価格", selling_price: "販売価格", category: "カテゴリ", stock_status: "在庫状況", in_stock: "在庫あり", out_of_stock: "在庫なし", update_stock: "在庫更新",
    total_balance: "残高", income: "収入", expense: "支出", add_expense: "支出追加", category_name: "カテゴリ名", amount: "金額", date: "日付", description: "説明",
    shipping_status: "配送状況", track_order: "追跡", tracking_id: "追跡ID", delivery_charge: "送料", courier_name: "業者名",
    ad_cost: "広告費", conversion_rate: "コンバージョン率", reach: "リーチ", leads: "リード", campaign_name: "キャンペーン名", marketing_roi: "マーケティングROI"
  }
};

const baseDir = path.join(__dirname, 'public', 'locales');

Object.keys(locales).forEach(lang => {
  const dir = path.join(baseDir, lang);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(
    path.join(dir, 'common.json'),
    JSON.stringify(locales[lang], null, 2),
    'utf8'
  );
  console.log(`✅ Success: ${lang}/common.json (${Object.keys(locales[lang]).length} keys)`);
});

console.log("\n🚀 All 10 dictionaries are synchronized and ready for Global SaaS launch!");